# Generated by Django 5.1.15 on 2026-08-14 23:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('name', models.CharField(db_index=True, help_text='Human-readable name of the WordPress project.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe slug identifier for the project.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the WordPress plugin requirements.')),
                ('plugin_slug', models.CharField(blank=True, default='', help_text="WordPress plugin folder/main-file slug (e.g. 'tersuite-affiliate').", max_length=100)),
                ('wordpress_version', models.CharField(default='6.7', help_text='Target WordPress core version.', max_length=20)),
                ('php_version', models.CharField(default='8.2', help_text='Target PHP runtime version.', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary project configuration, preferences, and tags.')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Soft-deletion/archival flag for the project.')),
                ('user', models.ForeignKey(help_text='User who owns this project.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'slug'), name='unique_user_project_slug')],
            },
        ),
    ]
