# Generated by Django 5.1.15 on 2026-08-19 07:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generations', '0003_generation_cancel_requested_at_and_more'),
        ('organizations', '0002_backfill_personal_organizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('run_number', models.PositiveIntegerField(default=1, help_text='Monotonically incrementing run number within the generation.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('CANCELLING', 'Cancelling'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed Out'), ('BLOCKED', 'Blocked')], db_index=True, default='PENDING', help_text='Current state of the workflow run orchestration.', max_length=32)),
                ('state_version', models.PositiveBigIntegerField(default=0, help_text='Monotonically incrementing version for row-level concurrency control.')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when workflow run execution commenced.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when workflow run finished.', null=True)),
                ('paused_at', models.DateTimeField(blank=True, help_text='Timestamp when workflow run was paused.', null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, help_text='Timestamp when cancellation was requested.', null=True)),
                ('last_scheduler_heartbeat_at', models.DateTimeField(blank=True, help_text='Timestamp when the scheduler last evaluated this run.', null=True)),
                ('failure_category', models.CharField(blank=True, default='', help_text='Failure classification if workflow run failed.', max_length=50)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if workflow run failed.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Workflow execution metadata and parameters.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generation', models.ForeignKey(help_text='Parent generation this workflow run executes.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='generations.generation')),
                ('organization', models.ForeignKey(help_text='Tenant organization that owns this resource.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Run',
                'verbose_name_plural': 'Workflow Runs',
                'ordering': ['-run_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('key', models.CharField(db_index=True, help_text='Stable logical key unique within the workflow run.', max_length=128)),
                ('name', models.CharField(help_text='Descriptive task name.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('LEASED', 'Leased'), ('RUNNING', 'Running'), ('CANDIDATE_COMPLETE', 'Candidate Complete'), ('COMPLETED', 'Completed'), ('RETRY_WAIT', 'Retry Wait'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('CANCELLING', 'Cancelling'), ('CANCELLED', 'Cancelled'), ('TIMED_OUT', 'Timed Out')], db_index=True, default='PENDING', help_text='Current state of the work package.', max_length=32)),
                ('priority', models.IntegerField(db_index=True, default=100, help_text='Execution priority (higher value executed first).')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum allowed attempts before terminal failure.')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Total number of execution attempts initiated.')),
                ('timeout_seconds', models.PositiveIntegerField(default=600, help_text='Maximum execution duration per attempt in seconds.')),
                ('retry_base_seconds', models.PositiveIntegerField(default=30, help_text='Base backoff duration for retries in seconds.')),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when next attempt can be claimed after retry backoff.', null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, help_text='Timestamp when cancellation was requested for this package.', null=True)),
                ('input_payload', models.JSONField(blank=True, default=dict, help_text='Input data, context, and requirements passed to worker.')),
                ('result_payload', models.JSONField(blank=True, default=dict, help_text='Candidate output produced by worker.')),
                ('validation_evidence', models.JSONField(blank=True, default=dict, help_text='Deterministic verification proof required for completion.')),
                ('failure_category', models.CharField(blank=True, default='', help_text='Classified category of failure.', max_length=50)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if package execution failed.')),
                ('ready_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when dependencies resolved and package became READY.', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when first execution attempt started.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when validated completion occurred.', null=True)),
                ('state_version', models.PositiveBigIntegerField(default=0, help_text='Monotonically incrementing version for row-level concurrency control.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generation_step', models.ForeignKey(blank=True, help_text='Optional link to parent generation step.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_packages', to='generations.generationstep')),
                ('organization', models.ForeignKey(help_text='Tenant organization that owns this resource.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workflow_run', models.ForeignKey(help_text='Workflow run this package belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='workflows.workflowrun')),
            ],
            options={
                'verbose_name': 'Work Package',
                'verbose_name_plural': 'Work Packages',
                'ordering': ['-priority', 'ready_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkPackageAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('attempt_number', models.PositiveIntegerField(help_text='1-indexed attempt number for the package.')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('CANDIDATE_COMPLETE', 'Candidate Complete'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed Out'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', help_text='Status of this attempt.', max_length=32)),
                ('worker_id', models.CharField(db_index=True, help_text='Identifier of worker or agent claiming this attempt.', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when attempt execution began.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when attempt completed or terminated.', null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, help_text='Timestamp of most recent worker heartbeat.', null=True)),
                ('retryable', models.BooleanField(default=True, help_text='Whether a failure on this attempt is eligible for retry.')),
                ('failure_category', models.CharField(blank=True, default='', help_text='Failure classification.', max_length=50)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Diagnostic failure details and traceback.')),
                ('result_payload', models.JSONField(blank=True, default=dict, help_text='Output payload produced by worker on this attempt.')),
                ('work_package', models.ForeignKey(help_text='Parent work package.', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='workflows.workpackage')),
            ],
            options={
                'verbose_name': 'Work Package Attempt',
                'verbose_name_plural': 'Work Package Attempts',
                'ordering': ['attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkPackageDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('dependency_type', models.CharField(choices=[('HARD', 'Hard Dependency'), ('SOFT', 'Soft Dependency')], default='HARD', help_text='HARD blocks successor; SOFT provides advisory ordering.', max_length=20)),
                ('predecessor', models.ForeignKey(help_text='Package that must complete before successor can become ready.', on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='workflows.workpackage')),
                ('successor', models.ForeignKey(help_text='Package that depends on predecessor.', on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='workflows.workpackage')),
                ('workflow_run', models.ForeignKey(help_text='Workflow run containing this DAG edge.', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='workflows.workflowrun')),
            ],
            options={
                'verbose_name': 'Work Package Dependency',
                'verbose_name_plural': 'Work Package Dependencies',
            },
        ),
        migrations.CreateModel(
            name='WorkPackageLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('lease_token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Opaque secret token required for heartbeat and release.', unique=True)),
                ('worker_id', models.CharField(db_index=True, help_text='Worker identifier holding this lease.', max_length=255)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when lease was granted.')),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when lease was last refreshed.')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Timestamp after which lease is considered stale and reapable.')),
                ('released_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when lease was released.', null=True)),
                ('release_reason', models.CharField(blank=True, choices=[('COMPLETED', 'Candidate Complete'), ('FAILED', 'Execution Failed'), ('EXPIRED', 'Lease Expired'), ('CANCELLED', 'Cancelled'), ('WORKER_SHUTDOWN', 'Worker Shutdown')], default='', help_text='Reason recorded upon lease release.', max_length=50)),
                ('attempt', models.ForeignKey(help_text='Attempt this lease is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='workflows.workpackageattempt')),
                ('work_package', models.ForeignKey(help_text='Work package covered by this lease.', on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='workflows.workpackage')),
            ],
            options={
                'verbose_name': 'Work Package Lease',
                'verbose_name_plural': 'Work Package Leases',
                'ordering': ['-acquired_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Stable event identifier across delivery attempts.', unique=True)),
                ('aggregate_type', models.CharField(db_index=True, help_text="Aggregate domain classification (e.g. 'generation', 'workflow', 'work_package').", max_length=64)),
                ('aggregate_id', models.CharField(db_index=True, help_text='String ID of aggregate entity.', max_length=64)),
                ('event_type', models.CharField(db_index=True, help_text='Normalized event type string.', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Event payload dictionary.')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when domain event occurred.')),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Earliest timestamp when event can be claimed for dispatch.')),
                ('claim_token', models.UUIDField(blank=True, db_index=True, help_text='Opaque token assigned to the claiming dispatcher worker.', null=True)),
                ('claimed_until', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when dispatcher claim lease expires.', null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when event was acknowledged published to transport.', null=True)),
                ('publish_attempts', models.PositiveIntegerField(default=0, help_text='Total delivery attempts.')),
                ('last_error', models.TextField(blank=True, default='', help_text='Error message from last failed publish attempt.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generation', models.ForeignKey(blank=True, help_text='Associated generation if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='generations.generation')),
                ('organization', models.ForeignKey(help_text='Tenant organization that owns this resource.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outbox Event',
                'verbose_name_plural': 'Outbox Events',
                'ordering': ['available_at', 'id'],
                'indexes': [models.Index(fields=['published_at', 'available_at'], name='workflows_o_publish_91f76f_idx'), models.Index(fields=['claimed_until', 'published_at'], name='workflows_o_claimed_28f51d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('command_type', models.CharField(choices=[('PAUSE', 'Pause'), ('RESUME', 'Resume'), ('CANCEL', 'Cancel'), ('RETRY', 'Retry')], db_index=True, help_text='Command type (PAUSE, RESUME, CANCEL, RETRY).', max_length=32)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Client-supplied idempotency key.', max_length=128)),
                ('request_hash', models.CharField(db_index=True, help_text='SHA-256 hash of canonical request parameters.', max_length=64)),
                ('request_payload', models.JSONField(blank=True, default=dict, help_text='Sanitized request payload.')),
                ('response_payload', models.JSONField(blank=True, default=dict, help_text='Stored response for idempotent replay.')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('FAILED', 'Failed')], default='APPLIED', help_text='Outcome status of the command.', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when command was applied.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generation', models.ForeignKey(help_text='Target generation for this command.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_commands', to='generations.generation')),
                ('organization', models.ForeignKey(help_text='Tenant organization that owns this resource.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Command',
                'verbose_name_plural': 'Workflow Commands',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='unique_organization_command_idempotency_key')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['organization', 'status'], name='workflows_w_organiz_fd4964_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['generation', 'status'], name='workflows_w_generat_455ddb_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowrun',
            constraint=models.UniqueConstraint(fields=('generation', 'run_number'), name='unique_generation_run_number'),
        ),
        migrations.AddIndex(
            model_name='workpackage',
            index=models.Index(fields=['status', 'priority', 'ready_at'], name='workflows_w_status_c7593b_idx'),
        ),
        migrations.AddIndex(
            model_name='workpackage',
            index=models.Index(fields=['workflow_run', 'status'], name='workflows_w_workflo_84d191_idx'),
        ),
        migrations.AddConstraint(
            model_name='workpackage',
            constraint=models.UniqueConstraint(fields=('workflow_run', 'key'), name='unique_workflow_run_package_key'),
        ),
        migrations.AddConstraint(
            model_name='workpackageattempt',
            constraint=models.UniqueConstraint(fields=('work_package', 'attempt_number'), name='unique_package_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='workpackagedependency',
            constraint=models.UniqueConstraint(fields=('predecessor', 'successor'), name='unique_package_dependency_edge'),
        ),
        migrations.AddConstraint(
            model_name='workpackagelease',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('work_package',), name='unique_active_lease_per_package'),
        ),
    ]
