# Generated by Django 5.1.15 on 2026-08-14 23:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('run_number', models.PositiveIntegerField(default=1, help_text='Attempt number for this step (1, 2, 3...).')),
                ('runtime_type', models.CharField(default='openhands', help_text="The runtime adapter executing this run (e.g. 'openhands', 'mock').", max_length=50)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', help_text='TersuiteAgentRuntime internal session identifier.', max_length=255)),
                ('remote_conversation_id', models.CharField(blank=True, db_index=True, default='', help_text='OpenHands Agent Server remote conversation UUID.', max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMED_OUT', 'Timed Out')], db_index=True, default='QUEUED', help_text='Execution status of this agent run attempt.', max_length=30)),
                ('model_name', models.CharField(blank=True, default='', help_text='LLM model identifier used for this run.', max_length=150)),
                ('prompt', models.TextField(help_text='Exact prompt and instruction sent to the agent.')),
                ('output', models.TextField(blank=True, default='', help_text='Final text output or response produced by the agent.')),
                ('token_usage', models.JSONField(blank=True, default=dict, help_text='Token consumption stats (prompt_tokens, completion_tokens, total).')),
                ('failure_category', models.CharField(blank=True, default='', help_text='Failure categorization if execution failed.', max_length=50)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Structured traceback and failure diagnostics.')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when run started.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when run ended.', null=True)),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'ordering': ['run_number'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('prompt', models.TextField(help_text='Initial natural language prompt or requirements from user.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SPECIFICATION', 'Specification'), ('APPROVED', 'Approved'), ('PLANNING', 'Planning'), ('BUILDING', 'Building'), ('TESTING', 'Testing'), ('REVIEW', 'Review'), ('PACKAGING', 'Packaging'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused'), ('RETRYING', 'Retrying')], db_index=True, default='DRAFT', help_text='Current state in the generation lifecycle machine.', max_length=30)),
                ('current_step_number', models.PositiveIntegerField(default=0, help_text='Index of the currently active generation step.')),
                ('total_steps', models.PositiveIntegerField(default=0, help_text='Total number of steps planned for this generation.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Config settings, model preferences, and domain tags.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Human-readable error details if generation failed.')),
                ('failure_category', models.CharField(blank=True, default='', help_text='Classified category of failure (e.g. MODEL_ERROR, TIMEOUT, etc.).', max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when generation successfully finished packaging.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when generation was cancelled.', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='Timestamp when generation encountered an unrecoverable failure.', null=True)),
                ('paused_at', models.DateTimeField(blank=True, help_text='Timestamp when generation was temporarily paused.', null=True)),
                ('project', models.ForeignKey(help_text='Parent project for this generation.', on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='projects.project')),
                ('user', models.ForeignKey(help_text='User who initiated this generation.', on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generation',
                'verbose_name_plural': 'Generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('name', models.CharField(db_index=True, help_text='Human-readable filename of the artifact.', max_length=255)),
                ('file_path', models.CharField(help_text='Relative path inside the WordPress plugin structure.', max_length=512)),
                ('artifact_type', models.CharField(choices=[('SOURCE_CODE', 'Source Code File'), ('CONFIGURATION', 'Configuration File'), ('TEST_REPORT', 'Test & Verification Report'), ('DOCUMENTATION', 'Documentation / Readme'), ('ZIP_ARCHIVE', 'ZIP Archive Package'), ('SECURITY_REPORT', 'Security Audit Report'), ('OTHER', 'Other Output')], db_index=True, default='SOURCE_CODE', help_text='Category of the artifact.', max_length=50)),
                ('mime_type', models.CharField(default='text/plain', help_text='MIME content type of the artifact.', max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0, help_text='File size in bytes.')),
                ('checksum_sha256', models.CharField(blank=True, default='', help_text='SHA-256 cryptographic checksum of the file content.', max_length=64)),
                ('storage_backend', models.CharField(default='local_filesystem', help_text='Storage provider backend used to persist the file.', max_length=50)),
                ('storage_key', models.CharField(help_text='Lookup key or URI within the storage backend.', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='File attributes, syntax status, lines of code, and audit tags.')),
                ('agent_run', models.ForeignKey(blank=True, help_text='Agent run attempt that generated this artifact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='generations.agentrun')),
                ('generation', models.ForeignKey(help_text='Generation that produced this artifact.', on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='generations.generation')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('step_number', models.PositiveIntegerField(help_text='Order index of this step within the generation sequence (1-indexed).')),
                ('name', models.CharField(help_text="Descriptive name of the step (e.g. 'WordPress Architecture Blueprint').", max_length=255)),
                ('agent_role', models.CharField(help_text="Designated agent domain role (e.g. 'architect', 'coder', 'security').", max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', help_text='Current state of this step.', max_length=30)),
                ('input_payload', models.JSONField(blank=True, default=dict, help_text='Input contracts, context, or specification passed to this step.')),
                ('output_payload', models.JSONField(blank=True, default=dict, help_text='Output data, architecture plan, or code metadata generated by this step.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if step failed.')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when step execution commenced.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when step completed or terminated.', null=True)),
                ('generation', models.ForeignKey(help_text='Generation this step belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='generations.generation')),
            ],
            options={
                'verbose_name': 'Generation Step',
                'verbose_name_plural': 'Generation Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='step',
            field=models.ForeignKey(help_text='The generation step this run executes.', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='generations.generationstep'),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('workspace_path', models.CharField(help_text='Isolated filesystem path or relative workspace identifier.', max_length=512)),
                ('storage_type', models.CharField(choices=[('LOCAL', 'Local File System'), ('EPHEMERAL_CONTAINER', 'Ephemeral Container'), ('REMOTE_STORAGE', 'Remote Object Storage')], default='LOCAL', help_text='Isolation storage backend backing this workspace.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workspace is active and mounted.')),
                ('disk_usage_bytes', models.BigIntegerField(default=0, help_text='Calculated disk space consumption in bytes.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Workspace container IDs, mount points, and environment tags.')),
                ('generation', models.OneToOneField(help_text='Generation this workspace belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='generations.generation')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
            },
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['project', 'status'], name='generations_project_7b6066_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['user', 'status'], name='generations_user_id_e6cabc_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['generation', 'artifact_type'], name='generations_generat_0f312e_idx'),
        ),
        migrations.AddConstraint(
            model_name='generationstep',
            constraint=models.UniqueConstraint(fields=('generation', 'step_number'), name='unique_generation_step_number'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(fields=('step', 'run_number'), name='unique_step_run_number'),
        ),
    ]
