# Generated by Django 5.1.15 on 2026-08-19 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_generation_states_forward(apps, schema_editor):
    Generation = apps.get_model("generations", "Generation")
    GenerationStateTransition = apps.get_model("generations", "GenerationStateTransition")

    status_map = {
        "SPECIFICATION": "SPECIFICATION_DRAFT",
        "PLANNING": "PLAN_DRAFT",
        "TESTING": "SANDBOX_QA",
        "REVIEW": "REVIEWING",
        "PACKAGING": "RELEASE_CANDIDATE",
        "RETRYING": "SCHEDULED",
    }

    for gen in Generation.objects.all():
        if gen.status in status_map:
            gen.status = status_map[gen.status]
        if not gen.status_changed_at:
            gen.status_changed_at = gen.updated_at or gen.created_at
        if gen.state_version == 0:
            gen.state_version = 1
        gen.next_transition_sequence = 2
        gen.save(update_fields=["status", "status_changed_at", "state_version", "next_transition_sequence"])

        # Create initial baseline transition record
        GenerationStateTransition.objects.get_or_create(
            generation=gen,
            sequence=1,
            defaults={
                "from_status": "",
                "to_status": gen.status,
                "reason": "Baseline state migration backfill",
            },
        )


def backfill_generation_states_reverse(apps, schema_editor):
    Generation = apps.get_model("generations", "Generation")

    reverse_status_map = {
        "SPECIFICATION_DRAFT": "SPECIFICATION",
        "SPECIFICATION_REFINED": "SPECIFICATION",
        "PLAN_DRAFT": "PLANNING",
        "PLAN_APPROVED": "PLANNING",
        "SANDBOX_QA": "TESTING",
        "REVIEWING": "REVIEW",
        "CORRECTING": "BUILDING",
        "RELEASE_CANDIDATE": "PACKAGING",
        "AWAITING_DEPLOYMENT_APPROVAL": "COMPLETED",
        "STAGED": "COMPLETED",
        "ACTIVE": "COMPLETED",
        "SCHEDULED": "RETRYING",
        "CANCELLING": "CANCELLED",
        "TIMED_OUT": "FAILED",
        "BLOCKED": "FAILED",
        "ROLLED_BACK": "CANCELLED",
        "SUPERSEDED": "CANCELLED",
    }

    for gen in Generation.objects.all():
        if gen.status in reverse_status_map:
            gen.status = reverse_status_map[gen.status]
            gen.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0002_organization_audit_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when cancellation was requested.', null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='next_transition_sequence',
            field=models.PositiveBigIntegerField(default=1, help_text='Monotonically increasing sequence number for state transitions.'),
        ),
        migrations.AddField(
            model_name='generation',
            name='resume_status',
            field=models.CharField(blank=True, help_text='Saved status prior to entering PAUSED state.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='state_version',
            field=models.PositiveBigIntegerField(default=0, help_text='Monotonically incrementing version for row concurrency control.'),
        ),
        migrations.AddField(
            model_name='generation',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the status last transitioned.', null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='timed_out_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when generation timed out.', null=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when generation reached RELEASE_CANDIDATE.', null=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DISCOVERY', 'Discovery'), ('SPECIFICATION_DRAFT', 'Specification Draft'), ('PLAN_DRAFT', 'Plan Draft'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('BUILDING', 'Building'), ('INTEGRATING', 'Integrating'), ('REVIEWING', 'Reviewing'), ('CORRECTING', 'Correcting'), ('SANDBOX_QA', 'Sandbox QA'), ('RELEASE_CANDIDATE', 'Release Candidate'), ('AWAITING_DEPLOYMENT_APPROVAL', 'Awaiting Deployment Approval'), ('STAGED', 'Staged'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLING', 'Cancelling'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed Out'), ('BLOCKED', 'Blocked'), ('ROLLED_BACK', 'Rolled Back'), ('SUPERSEDED', 'Superseded')], db_index=True, default='DRAFT', help_text='Current canonical state in the generation lifecycle machine.', max_length=64),
        ),
        migrations.AlterField(
            model_name='generationstep',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('CANDIDATE_COMPLETE', 'Candidate Complete'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled'), ('TIMED_OUT', 'Timed Out'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', help_text='Current state of this step.', max_length=30),
        ),
        migrations.CreateModel(
            name='GenerationMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('sequence', models.PositiveIntegerField(help_text='Order index of this milestone within the generation sequence (1-indexed).')),
                ('name', models.CharField(help_text='Descriptive name of the milestone.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current state of this milestone.', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Milestone metadata and scope details.')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when milestone execution commenced.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when milestone completed.', null=True)),
                ('generation', models.ForeignKey(help_text='Generation this milestone belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='generations.generation')),
            ],
            options={
                'verbose_name': 'Generation Milestone',
                'verbose_name_plural': 'Generation Milestones',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='generationstep',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='Milestone container this step belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='generations.generationmilestone'),
        ),
        migrations.CreateModel(
            name='GenerationStateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('sequence', models.PositiveBigIntegerField(help_text='Monotonically increasing sequence number within the generation.')),
                ('from_status', models.CharField(help_text='Origin status before transition.', max_length=64)),
                ('to_status', models.CharField(help_text='Target status after transition.', max_length=64)),
                ('command_id', models.UUIDField(blank=True, db_index=True, help_text='Associated command ID if initiated by an idempotent command.', null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason or trigger for this transition.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contextual metadata recorded at transition time.')),
                ('actor', models.ForeignKey(blank=True, help_text='User who initiated or authorized this transition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_transitions', to=settings.AUTH_USER_MODEL)),
                ('generation', models.ForeignKey(help_text='Generation this transition belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='generations.generation')),
            ],
            options={
                'verbose_name': 'Generation State Transition',
                'verbose_name_plural': 'Generation State Transitions',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='generationmilestone',
            constraint=models.UniqueConstraint(fields=('generation', 'sequence'), name='unique_generation_milestone_sequence'),
        ),
        migrations.AddConstraint(
            model_name='generationstatetransition',
            constraint=models.UniqueConstraint(fields=('generation', 'sequence'), name='unique_generation_transition_sequence'),
        ),
        migrations.RunPython(
            code=backfill_generation_states_forward,
            reverse_code=backfill_generation_states_reverse,
        ),
    ]
